# Generated by Django 3.1 on 2023-10-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='empty', max_length=100),
            preserve_default=False,
        ),
    ]
